import { boolean, integer, pgTable, text, timestamp } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const curricula = pgTable('curricula', { id: integer('id').generatedAlwaysAsIdentity().primaryKey(), userId: text('userId').notNull(), grade: integer('grade').notNull(), title: text('title').notNull(), lessonCount: integer('lessonCount').notNull().default(0), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const classes = pgTable('classes', { id: integer('id').generatedAlwaysAsIdentity().primaryKey(), userId: text('userId').notNull(), name: text('name').notNull(), grade: integer('grade').notNull(), teacher: text('teacher').notNull(), weeklyPeriods: integer('weeklyPeriods').notNull().default(2), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const lessons = pgTable('lessons', { id: integer('id').generatedAlwaysAsIdentity().primaryKey(), userId: text('userId').notNull(), classId: integer('classId').notNull(), week: integer('week').notNull(), day: text('day').notNull(), period: integer('period').notNull(), title: text('title').notNull(), status: text('status').notNull().default('Bình thường'), note: text('note') })
export const settings = pgTable('settings', { id: integer('id').generatedAlwaysAsIdentity().primaryKey(), userId: text('userId').notNull(), schoolYear: text('schoolYear').notNull().default('2026 – 2027'), startDate: text('startDate'), totalWeeks: integer('totalWeeks').notNull().default(35), teacherName: text('teacherName') })
