'use client'
import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import { authClient } from '@/lib/auth-client'

export default function SignInPage() {
  const router = useRouter(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [signup,setSignup]=useState(false); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); const result = signup ? await authClient.signUp.email({ email, password, name }) : await authClient.signIn.email({ email, password }); if (result.error) setError('Không thể đăng nhập. Vui lòng kiểm tra lại thông tin.'); else { router.push('/'); router.refresh() } setBusy(false) }
  return <main className="flex min-h-screen items-center justify-center bg-background p-6"><form onSubmit={submit} className="w-full max-w-md space-y-6 rounded-2xl border border-border bg-card p-8 shadow-sm"><div><p className="text-sm font-semibold text-primary">Kế hoạch dạy học</p><h1 className="mt-2 text-2xl font-semibold">{signup ? 'Tạo tài khoản' : 'Đăng nhập'}</h1><p className="mt-2 text-sm text-muted-foreground">Quản lý PPCT, thời khóa biểu và tiến độ giảng dạy.</p></div>{signup && <label className="block text-sm">Họ và tên<input required value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-lg border border-input bg-background px-3 py-2" /></label>}<label className="block text-sm">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-lg border border-input bg-background px-3 py-2" /></label><label className="block text-sm">Mật khẩu<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-lg border border-input bg-background px-3 py-2" /></label>{error && <p className="text-sm text-destructive">{error}</p>}<button disabled={busy} className="w-full rounded-lg bg-primary px-4 py-2.5 font-medium text-primary-foreground disabled:opacity-60">{busy ? 'Đang xử lý...' : signup ? 'Tạo tài khoản' : 'Đăng nhập'}</button><button type="button" onClick={()=>setSignup(!signup)} className="w-full text-sm text-primary">{signup ? 'Đã có tài khoản? Đăng nhập' : 'Chưa có tài khoản? Đăng ký'}</button></form></main>
}
